---

fortishield_manager_version: 4.8.0

fortishield_manager_fqdn: "fortishield-server"
fortishield_manager_package_state: present

# Custom packages installation
fortishield_custom_packages_installation_manager_enabled: false
fortishield_custom_packages_installation_manager_deb_url: "https://s3-us-west-1.amazonaws.com/fortishield.github.io/packages-dev/"
fortishield_custom_packages_installation_manager_rpm_url: "https://s3-us-west-1.amazonaws.com/fortishield.github.io/packages-dev/"

# Sources installation
fortishield_manager_sources_installation:
  enabled: false
  branch: "v4.4.4"
  user_language: "en"
  user_no_stop: "y"
  user_install_type: "server"
  user_dir: "/var/ossec"
  user_delete_dir: null
  user_enable_active_response: null
  user_enable_syscheck: "y"
  user_enable_rootcheck: "y"
  user_enable_openscap: "n"
  user_enable_authd: "y"
  user_generate_authd_cert: null
  user_update: "y"
  user_binaryinstall: null
  user_enable_email: "n"
  user_auto_start: "y"
  user_email_address: null
  user_email_smpt: null
  user_enable_syslog: "n"
  user_white_list: "n"
  user_ca_store: null
  threads: "2"

fortishield_dir: "/var/ossec"

##########################################
### Fortishield-OSSEC
##########################################

# groups to create
agent_groups: []

## Global
fortishield_manager_json_output: 'yes'
fortishield_manager_alerts_log: 'yes'
fortishield_manager_logall: 'no'
fortishield_manager_logall_json: 'no'

fortishield_manager_email_notification: 'no'
fortishield_manager_mailto:
  - 'admin@example.net'

fortishield_manager_email_smtp_server: smtp.example.fortishield.github.io
fortishield_manager_email_from: fortishield@example.fortishield.github.io
fortishield_manager_email_maxperhour: 12
fortishield_manager_email_queue_size: 131072
fortishield_manager_email_log_source: 'alerts.log'

fortishield_manager_globals:
  - '127.0.0.1'
  - '^localhost.localdomain$'
  - '127.0.0.53'

fortishield_manager_agent_disconnection_time: '20s'
fortishield_manager_agents_disconnection_alert_time: '100s'

## Alerts
fortishield_manager_log_level: 3
fortishield_manager_email_level: 12

## Logging
fortishield_manager_log_format: 'plain'

## Email alerts
fortishield_manager_extra_emails:
  - enable: false
    mail_to: 'recipient@example.fortishield.github.io'
    format: full
    level: 7
    event_location: null
    group: null
    do_not_delay: false
    do_not_group: false
    rule_id: null


## Remote
fortishield_manager_connection:
  - type: 'secure'
    port: '1514'
    protocol: 'tcp'
    queue_size: 131072

## Reports
fortishield_manager_reports:
  - enable: false
    category: 'syscheck'
    title: 'Daily report: File changes'
    email_to: 'recipient@example.fortishield.github.io'
    location: null
    group: null
    rule: null
    level: null
    srcip: null
    user: null
    showlogs: null

## Woodles
fortishield_manager_rootcheck:
  frequency: 43200

fortishield_manager_openscap:
  disable: 'yes'
  timeout: 1800
  interval: '1d'
  scan_on_start: 'yes'

fortishield_manager_ciscat:
  disable: 'yes'
  install_java: 'yes'
  timeout: 1800
  interval: '1d'
  scan_on_start: 'yes'
  java_path: '/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/bin'
  ciscat_path: 'wodles/ciscat'

fortishield_manager_osquery:
  disable: 'yes'
  run_daemon: 'yes'
  log_path: '/var/log/osquery/osqueryd.results.log'
  config_path: '/etc/osquery/osquery.conf'
  ad_labels: 'yes'

fortishield_manager_syscollector:
  disable: 'no'
  interval: '1h'
  scan_on_start: 'yes'
  hardware: 'yes'
  os: 'yes'
  network: 'yes'
  packages: 'yes'
  ports_no: 'yes'
  processes: 'yes'

fortishield_manager_monitor_aws:
  disabled: 'yes'
  interval: '10m'
  run_on_start: 'yes'
  skip_on_error: 'yes'
  s3:
    - name: null
      bucket_type: null
      path: null
      only_logs_after: null
      access_key: null
      secret_key: null

## SCA
fortishield_manager_sca:
  enabled: 'yes'
  scan_on_start: 'yes'
  interval: '12h'
  skip_nfs: 'yes'
  day: ''
  wday: ''
  time: ''

## Vulnerability Detector
fortishield_manager_vulnerability_detector:
  enabled: 'no'
  index_status: 'no'
  feed_update_interval: '60m'

fortishield_manager_indexer:
  enabled: 'no'

## Syscheck
fortishield_manager_syscheck:
  disable: 'no'
  frequency: 43200
  scan_on_start: 'yes'
  auto_ignore: 'no'
  ignore:
    - /etc/mtab
    - /etc/hosts.deny
    - /etc/mail/statistics
    - /etc/random-seed
    - /etc/random.seed
    - /etc/adjtime
    - /etc/httpd/logs
    - /etc/utmpx
    - /etc/wtmpx
    - /etc/cups/certs
    - /etc/dumpdates
    - /etc/svc/volatile
  ignore_linux_type:
    - '.log$|.swp$'
  no_diff:
    - /etc/ssl/private.key
  directories:
    - dirs: /etc,/usr/bin,/usr/sbin
      checks: ''
    - dirs: /bin,/sbin,/boot
      checks: ''
  auto_ignore_frequency:
    frequency: 'frequency="10"'
    timeframe: 'timeframe="3600"'
    value: 'no'
  skip_nfs: 'yes'
  skip_dev: 'yes'
  skip_proc: 'yes'
  skip_sys: 'yes'
  process_priority: 10
  max_eps: 100
  sync_enabled: 'yes'
  sync_interval: '5m'
  sync_max_interval: '1h'
  sync_max_eps: 10

## Command
fortishield_manager_commands:
  - name: 'disable-account'
    executable: 'disable-account'
    timeout_allowed: 'yes'
  - name: 'restart-fortishield'
    executable: 'restart-fortishield'
  - name: 'firewall-drop'
    executable: 'firewall-drop'
    expect: 'srcip'
    timeout_allowed: 'yes'
  - name: 'host-deny'
    executable: 'host-deny'
    timeout_allowed: 'yes'
  - name: 'route-null'
    executable: 'route-null'
    timeout_allowed: 'yes'
  - name: 'win_route-null'
    executable: 'route-null.exe'
    timeout_allowed: 'yes'
  - name: 'netsh'
    executable: 'netsh.exe'
    timeout_allowed: 'yes'

## Localfile
fortishield_manager_localfiles:
  common:
    - format: 'command'
      command: df -P
      frequency: '360'
    - format: 'full_command'
      command: netstat -tulpn | sed 's/\([[:alnum:]]\+\)\ \+[[:digit:]]\+\ \+[[:digit:]]\+\ \+\(.*\):\([[:digit:]]*\)\ \+\([0-9\.\:\*]\+\).\+\ \([[:digit:]]*\/[[:alnum:]\-]*\).*/\1 \2 == \3 == \4 \5/' | sort -k 4 -g | sed 's/ == \(.*\) ==/:\1/' | sed 1,2d
      alias: 'netstat listening ports'
      frequency: '360'
    - format: 'full_command'
      command: 'last -n 20'
      frequency: '360'
    - format: 'syslog'
      location: "{{ fortishield_dir }}/logs/active-responses.log"
  debian:
    - format: 'syslog'
      location: '/var/log/auth.log'
    - format: 'syslog'
      location: '/var/log/syslog'
    - format: 'syslog'
      location: '/var/log/dpkg.log'
    - format: 'syslog'
      location: '/var/log/kern.log'
  centos:
    - format: 'syslog'
      location: '/var/log/messages'
    - format: 'syslog'
      location: '/var/log/secure'
    - format: 'syslog'
      location: '/var/log/maillog'
    - format: 'audit'
      location: '/var/log/audit/audit.log'

## Syslog outputs
fortishield_manager_syslog_outputs:
  - server: null
    port: null
    format: null

## Integrations
fortishield_manager_integrations:
  # slack
  - name: null
    hook_url: '<hook_url>'
    alert_level: 10
    alert_format: 'json'
    rule_id: null
  # pagerduty
  - name: null
    api_key: '<api_key>'
    alert_level: 12

## Labels
fortishield_manager_labels:
  enable: false
  list:
    - key: Env
      value: Production

## Ruleset
fortishield_manager_ruleset:
  rules_path: 'custom_ruleset/rules/'
  decoders_path: 'custom_ruleset/decoders/'
  cdb_lists:
    - 'audit-keys'
    - 'security-eventchannel'
    - 'amazon/aws-eventnames'

fortishield_manager_rule_exclude:
  - '0215-policy_rules.xml'

## Auth
fortishield_manager_authd:
  enable: true
  port: 1515
  use_source_ip: 'no'
  force:
    enabled: 'yes'
    key_mismatch: 'yes'
    disconnected_time: '1h'
    after_registration_time: '1h'
  purge: 'yes'
  use_password: 'no'
  ciphers: 'HIGH:!ADH:!EXP:!MD5:!RC4:!3DES:!CAMELLIA:@STRENGTH'
  ssl_agent_ca: null
  ssl_verify_host: 'no'
  ssl_manager_cert: 'sslmanager.cert'
  ssl_manager_key: 'sslmanager.key'
  ssl_auto_negotiate: 'no'

## Cluster
fortishield_manager_cluster:
  disable: 'yes'
  name: 'fortishield'
  node_name: 'manager_01'
  node_type: 'master'
  key: 'ugdtAnd7Pi9myP7CVts4qZaZQEQcRYZa'
  port: '1516'
  bind_addr: '0.0.0.0'
  nodes:
    - 'manager'
  hidden: 'no'

## Fortishield API setup
fortishield_manager_api:
  bind_addr: 0.0.0.0
  port: 55000
  behind_proxy_server: no
  https: yes
  https_key: "api/configuration/ssl/server.key"
  https_cert: "api/configuration/ssl/server.crt"
  https_use_ca: False
  https_ca: "api/configuration/ssl/ca.crt"
  logging_level: "info"
  logging_path: "logs/api.log"
  cors: no
  cors_source_route: "*"
  cors_expose_headers: "*"
  cors_allow_headers: "*"
  cors_allow_credentials: no
  cache: yes
  cache_time: 0.750
  access_max_login_attempts: 5
  access_block_time: 300
  access_max_request_per_minute: 300
  drop_privileges: yes
  experimental_features: no
  remote_commands_localfile: yes
  remote_commands_localfile_exceptions: []
  remote_commands_wodle: yes
  remote_commands_wodle_exceptions: []
# fortishield_api_users:
#   - username: custom-user
#     password: .S3cur3Pa55w0rd*- # Must comply with requirements (8+ length, uppercase, lowercase, specials chars)

# NOTE: As fortishield_manager_config is built dynamically per playbooks and ansible.cfg provided in the repo,
# we should also cover the case for partial settings in inventory variables overlayed on top of role's
# defaults with merge hash_behaviour. If you do a full replace instead of the hash_behaviour, set this to false.
#
# Please do notice this behaviour is deprecated in 2.13 and role will move away from it in future versions:
# https://docs.ansible.com/ansible/latest/reference_appendices/config.html#default-hash-behaviour
#
fortishield_manager_config_overlay: true

## Other/Wrappers
fortishield_manager_config_defaults:
  repo: '{{ fortishield_repo }}'
  json_output: '{{ fortishield_manager_json_output }}'
  alerts_log: '{{ fortishield_manager_alerts_log }}'
  logall: '{{ fortishield_manager_logall }}'
  logall_json: '{{ fortishield_manager_logall_json }}'
  log_format: '{{ fortishield_manager_log_format }}'
  api: '{{ fortishield_manager_api }}'
  cluster: '{{ fortishield_manager_cluster }}'
  connection: '{{ fortishield_manager_connection }}'
  authd: '{{ fortishield_manager_authd }}'
  email_notification: '{{ fortishield_manager_email_notification }}'
  mail_to: '{{ fortishield_manager_mailto }}'
  mail_smtp_server: '{{ fortishield_manager_email_smtp_server }}'
  mail_from: '{{ fortishield_manager_email_from }}'
  mail_maxperhour: '{{ fortishield_manager_email_maxperhour }}'
  mail_queue_size: '{{ fortishield_manager_email_queue_size }}'
  email_log_source: '{{ fortishield_manager_email_log_source }}'
  extra_emails: '{{ fortishield_manager_extra_emails }}'
  reports: '{{ fortishield_manager_reports}}'
  syscheck: '{{ fortishield_manager_syscheck }}'
  rootcheck: '{{ fortishield_manager_rootcheck }}'
  openscap: '{{ fortishield_manager_openscap }}'
  cis_cat: '{{ fortishield_manager_ciscat }}'
  osquery: '{{ fortishield_manager_osquery }}'
  syscollector: '{{ fortishield_manager_syscollector }}'
  sca: '{{ fortishield_manager_sca }}'
  vulnerability_detector: '{{ fortishield_manager_vulnerability_detector }}'
  indexer: '{{ fortishield_manager_indexer }}'
  log_level: '{{ fortishield_manager_log_level }}'
  email_level: '{{ fortishield_manager_email_level }}'
  localfiles: '{{ fortishield_manager_localfiles }}'
  globals: '{{ fortishield_manager_globals }}'
  commands: '{{ fortishield_manager_commands }}'
  ruleset: '{{ fortishield_manager_ruleset }}'
  rule_exclude: '{{ fortishield_manager_rule_exclude }}'
  syslog_outputs: '{{ fortishield_manager_syslog_outputs }}'
  integrations: '{{ fortishield_manager_integrations }}'
  monitor_aws: '{{ fortishield_manager_monitor_aws }}'
  labels: '{{ fortishield_manager_labels }}'
  agents_disconnection_time: '{{ fortishield_manager_agent_disconnection_time }}'
  agents_disconnection_alert_time: '{{ fortishield_manager_agents_disconnection_alert_time }}'

# shared-agent.conf

# shared_agent_config:
#   - type: os
#     type_value: Linux
#     syscheck:
#       frequency: 43200
#       scan_on_start: 'yes'
#       ignore:
#         - /etc/mtab
#         - /etc/mnttab
#         - /etc/hosts.deny
#         - /etc/mail/statistics
#         - /etc/svc/volatile
#       no_diff:
#         - /etc/ssl/private.key
#     rootcheck:
#       frequency: 43200
#       cis_distribution_filename: null
#     localfiles:
#       - format: 'syslog'
#         location: '/var/log/messages'
#       - format: 'syslog'
#         location: '/var/log/secure'
#       - format: 'syslog'
#         location: '/var/log/maillog'
#       - format: 'apache'
#         location: '/var/log/httpd/error_log'
#       - format: 'apache'
#         location: '/var/log/httpd/access_log'
#       - format: 'apache'
#         location: "{{ fortishield_dir }}/logs/active-responses.log"
#   - type: os
#     type_value: Windows
#     syscheck:
#       frequency: 43200
#       scan_on_start: 'yes'
#       auto_ignore: 'no'
#       windows_registry:
#         - key: 'HKEY_LOCAL_MACHINE\Software\Classes\batfile'
#           arch: 'both'
#         - key: 'HKEY_LOCAL_MACHINE\Software\Classes\Folder'
#     localfiles:
#       - location: 'Security'
#         format: 'eventchannel'
#       - location: 'System'
#         format: 'eventlog'
