- hosts: Agent*
  become: true
  tasks:
    - name: Modify Wazuh manager IP in Wazuh agent
      replace:
        path: "/var/ossec/etc/ossec.conf"
        regexp: "MANAGER_IP"
        replace: "{{ hostvars['Manager'].ansible_host }}"
    - name: Restart Wazuh agent
      command: "/var/ossec/bin/ossec-control restart"
