site_name: My Docs
theme:
  name: "material"

plugins:
  - search
  - mkdocstrings
nav:
    - Home: index.md
    - Deps: 
      - Dependencies: deps/deps.md
      - Wazuh Testing: 
        - Wazuh Testing: deps/wazuh-testing/wazuh_testing.md
        - Tools: deps/wazuh-testing/tools.md
    - Tests: 
      - Index: tests/tests.md
      - Integration: 
        - Index: tests/integration/integration.md
        - Vulnerability Detector: 
          - Index: tests/integration/vulnerability-detector/vulnerability-detector.md
          - Tests feeds: 
            - Index: tests/integration/vulnerability-detector/feeds/feeds.md
            - Debian: tests/integration/vulnerability-detector/feeds/debian/debian.md
            - RedHat: tests/integration/vulnerability-detector/feeds/redhat/redhat.md
            - MSU: tests/integration/vulnerability-detector/feeds/msu/msu.md
            - Canonical: tests/integration/vulnerability-detector/feeds/canonical/canonical.md
            - Download feeds: tests/integration/vulnerability-detector/feeds/download-feed.md
            - Invalid type custom feeds: tests/integration/vulnerability-detector/feeds/invalid-type-custom-feeds.md
            - Invalid type url feeds: tests/integration/vulnerability-detector/feeds/invalid-type-url-feeds.md
            - Validate feed content: tests/integration/vulnerability-detector/feeds/validate-feed-content.md
          - Tests general settings:  tests/integration/vulnerability-detector/general-settings/general-settings.md
          - Tests providers: tests/integration/vulnerability-detector/providers/test-providers.md
          - Tests SCAN results: tests/integration/vulnerability-detector/scan-results/scan-results.md
          - Tests Windows: tests/integration/vulnerability-detector/windows/windows.md







