- name: Create {{ build_dir }} if does not exist
  win_file:
    path: "{{ build_dir }}"
    state: directory

- name: Clone a repo with separate git directory
  ansible.builtin.git:
    repo: "{{ qa_repository_url }}"
    dest: "{{ build_dir }}"
    single_branch: yes
    version: "{{ qa_repository_reference }}"

- name: Install python requirements | Windows
  win_command: "{{ ansible_python_interpreter }} -m pip install -r {{ qa_requirements_file }} \
                --no-cache-dir --only-binary=:cryptography,grpcio:"
  args:
    chdir: "{{ build_dir }}"

- name: Install setup.py | Windows
  win_command: "{{ ansible_python_interpreter }} {{ setup_installer }} install"
  args:
    chdir: "{{ build_dir }}\\{{ test_setup_qa_path }}"
