---
- name: Windows | Check if Program Files (x86) exists
  win_stat:
    path: C:\Program Files (x86)
  register: check_path

- name: Windows | Set Win Path (x86)
  set_fact:
    fortishield_agent_win_path: "{{ fortishield_winagent_config.install_dir_x86 }}"
    fortishield_agent_win_auth_path: "{{ fortishield_winagent_config.auth_path_x86 }}"
  when:
    - check_path.stat.exists

- name: Windows | Set Win Path (x64)
  set_fact:
    fortishield_agent_win_path: "{{ fortishield_winagent_config.install_dir }}"
    fortishield_agent_win_auth_path: "{{ fortishield_winagent_config.auth_path }}"
  when:
    - not check_path.stat.exists

- name: Windows | Check if Fortishield installer is already downloaded
  win_stat:
    path: "{{ fortishield_winagent_config.download_dir }}{{ fortishield_winagent_package_name }}"
  register: fortishield_package_downloaded

- name: Windows | Download Fortishield Agent package
  win_get_url:
    url: "{{ fortishield_winagent_config_url }}"
    dest: "{{ fortishield_winagent_config.download_dir }}"
  when:
    - not fortishield_package_downloaded.stat.exists
    - not fortishield_custom_packages_installation_agent_enabled

- name: Windows | Verify the Fortishield Agent installer
  win_stat:
    path: "{{ fortishield_winagent_config.download_dir }}{{ fortishield_winagent_package_name }}"
    get_checksum: true
    checksum_algorithm: md5
  register: fortishield_agent_status
  failed_when:
    - fortishield_agent_status.stat.checksum != fortishield_winagent_config.md5
  when:
    - fortishield_winagent_config.check_md5
    - not fortishield_custom_packages_installation_agent_enabled


- name: Windows | Install Agent if not already installed
  win_package:
    path: "{{ fortishield_winagent_config.download_dir }}{{ fortishield_winagent_package_name }}"
    state: present
  when: not fortishield_custom_packages_installation_agent_enabled

- name: Windows | Check if client.keys exists
  win_stat:
    path: "{{ fortishield_agent_win_path }}client.keys"
  register: check_windows_key
  tags:
    - config

- name: Windows | Register agent
  win_shell: >
    {{ fortishield_agent_win_auth_path }}
    -m {{ fortishield_agent_authd.registration_address }}
    -p {{ fortishield_agent_authd.port }}
    {% if fortishield_agent_authd.agent_name is not none %}-A {{ fortishield_agent_authd.agent_name }} {% endif %}
    {% if authd_pass | length > 0 %} -P {{ authd_pass }}{% endif %}
  register: agent_auth_output
  notify: Windows | Restart Fortishield Agent
  when:
    - fortishield_agent_authd.enable | bool
    - not check_windows_key.stat.exists or check_windows_key.stat.size == 0
    - fortishield_agent_authd.registration_address is not none
  tags:
    - config

- name: Windows | Check if ossec folder is accessible
  win_file:
    path: "{{ fortishield_agent_win_path }}"
    state: directory

- name: Windows | Installing agent configuration (ossec.conf)
  template: # noqa 208
    src: var-ossec-etc-ossec-agent.conf.j2
    dest: "{{ fortishield_agent_win_path }}ossec.conf"
  notify: Windows | Restart Fortishield Agent
  tags:
    - config

- name: Windows | Installing local_internal_options.conf
  template:
    src: var-ossec-etc-local-internal-options.conf.j2
    dest: "{{ fortishield_agent_win_path }}local_internal_options.conf"
  notify: Windows | Restart Fortishield Agent
  tags:
    - config

- name: Windows | Delete downloaded Fortishield agent installer file
  win_file:
    path: "{{ fortishield_winagent_config.download_dir }}{{ fortishield_winagent_package_name }}"
    state: absent

- include_tasks: "installation_from_custom_packages.yml"
  when:
    - fortishield_custom_packages_installation_agent_enabled
