---

- name: Debian/Ubuntu | Remove Fortishield repository.
  apt_repository:
    repo: "{{ fortishield_manager_config.repo.apt }}"
    state: absent
  changed_when: false
  when: ansible_os_family == "Debian"

- name: RedHat/CentOS/Fedora | Remove Fortishield repository (and clean up left-over metadata)
  yum_repository:
    name: fortishield_repo
    state: absent
  changed_when: false
  when: ansible_os_family == "RedHat" or ansible_os_family == "Amazon"
