qa_repository_url: https://github.com/fortishield/fortishield-qa.git
qa_repository_reference: master
qa_requirements_file: requirements.txt
test_setup_qa_path: deps/fortishield_testing
setup_installer: setup.py
build_dir: /tmp/fortishield-qa
# This flag allows modifying any var
customize: false
