
- name: Update cache
  apt:
    update_cache: yes
  register: update_result
  until: update_result is success
  retries: 3
  delay: 10

- name: Debian 9 (Stretch)
  when: (ansible_facts['distribution'] == "Debian" and ansible_facts['distribution_major_version'] == "9")
  block:

    - name: Install Fortishield indexer dependencies
      apt:
        name: [
          'unzip', 'wget', 'curl', 'apt-transport-https', software-properties-common
        ]
        state: present

- name: Install fortishield-indexer
  block:
    - name: Add Fortishield indexer repository
      block:
        - name: Add apt repository signing key
          apt_key:
            url: "{{ fortishield_repo.gpg }}"
            state: present

        - name: Add Fortishield indexer repository
          apt_repository:
            repo: "{{ fortishield_repo.apt }}"
            state: present
            filename: 'fortishield-indexer'
            update_cache: yes

    - name: Install Fortishield indexer
      apt:
        name: fortishield-indexer={{ indexer_version }}-1
        state: present
      register: install
      tags: install
  when: not fortishield_custom_packages_installation_indexer_enabled

- include_tasks: "install_from_custom_package.yml"
  when:
    - fortishield_custom_packages_installation_indexer_enabled
