---
galaxy_info:
  author: Fortishield
  description: Installing, deploying and configuring Fortishield Manager.
  company: fortishield.github.io
  license: license (GPLv3)
  min_ansible_version: 2.0
  platforms:
    - name: EL
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Fedora
      versions:
        - all
  galaxy_tags:
    - monitoring
dependencies: []
