Project path: "../../tests/integration"

Output path: "../output"

Include paths:
  - "../../tests/integration/test_agentd"
  - "../../tests/integration/test_wazuh_db"
  - "../../tests/integration/test_vulnerability_detector"

Include regex:
  - "^test_.*py$"

Group files:
  - "README.md"

Function regex:
  - "^test_"

Ignore paths:
  - "../../tests/integration/test_agentd/data"
  - "../../tests/integration/test_wazuh_db/data"

Output fields:
  Module:
    Mandatory:
      - copyright
      - type
      - description
      - tiers
      - component
      - path
      - daemons
      - os_support
    Optional:
      - coverage
      - pytest_args
      - tags
  Test:
    Mandatory:
      - description
      - wazuh_min_version
      - assertions
      - test_input
      - logging
    Optional:
      - parameters
      - tags

Test cases field: test_cases
