Project path: "../../tests/integration"

Output path: "../output"

Include paths:
  - "../../tests/integration/test_wazuh_db"
  - "../../tests/integration/test_vulnerability_detector"

Include regex:
  - "^test_.*py$"

Group files:
  - "README.md"

Function regex:
  - "^test_"

Ignore paths:
  - "../../tests/integration/test_wazuh_db/data"

Output fields:
  Module:
    Mandatory:
      - Brief
      - Metadata:
        - Modules
        - Daemons
        - Operating System
        - Tiers
    Optional:
      - Tags
  Test:
    Mandatory:
      - Test Logic
      - Checks
    Optional:
      - Expected result

Test cases field: "Test Cases"
