Project path: "../../tests/integration"

Documentation path: "../output"

Include paths:
  - wazuh_db:
    path: "../../tests/integration/test_wazuh_db"
    recursive: false

Include regex:
  - "^test_.*py$"

Group files:
  - "README.md"

Function regex:
  - "^test_"

Ignore paths:
  - "../../tests/integration/test_wazuh_db/data"
  - "/data/*"

Output fields:
  Module:
    Mandatory:
      - Brief
      - Metadata
      - Modules
      - Daemons
      - Operating System
      - Tiers
    Optional:
      - Tags
  Test:
    Mandatory:
      - Test Logic
      - Checks
    Optional:
      - Expected result
