Project path: "../../tests/integration"

Output path: "../output"

Include paths:
  - "../../tests/integration/test_active_response"
  - "../../tests/integration/test_agentd"
  - "../../tests/integration/test_analysisd"

Include regex:
  - "^test_.*py$"

Group files:
  - "README.md"

Function regex:
  - "^test_"

Ignore paths:
  - "../../tests/integration/test_active_response/test_analysisd/data"
  - "../../tests/integration/test_active_response/test_execd/data"
  - "../../tests/integration/test_agentd/data"
  - "../../tests/integration/test_analysisd/test_all_syscheckd_configurations/data"
  - "../../tests/integration/test_analysisd/test_all_syscheckd_configurations/yaml_generators"
  - "../../tests/integration/test_analysisd/test_error_messages/data"
  - "../../tests/integration/test_analysisd/test_event_messages/data"
  - "../../tests/integration/test_analysisd/test_integrity_messages/data"
  - "../../tests/integration/test_analysisd/test_mitre/data"
  - "../../tests/integration/test_analysisd/test_scan_messages/data"

Output fields:
  Module:
    Mandatory:
      - copyright
      - type
      - description
      - tiers
      - component
      - path
      - daemons
      - os_support
    Optional:
      - coverage
      - pytest_args
      - tags
  Test:
    Mandatory:
      - description
      - wazuh_min_version
      - assertions
      - test_input
      - logging
    Optional:
      - parameters
      - tags

Test cases field: test_cases
