- name: Download agent package
  get_url:
    url: "{{ fortishield_custom_packages_installation_agent_macos_url }}"
    dest: /Users/vagrant
    validate_certs: no

- include_tasks: "installation_from_custom_packages.yml"
  when: fortishield_custom_packages_installation_agent_enabled

- name: macOS | Set agent configuration (ossec.conf)
  template:
    src: var-ossec-etc-ossec-agent.conf.j2
    dest: "{{ macos_fortishield_dir }}/etc/ossec.conf"
    owner: root
    group: fortishield
    mode: 0644
  notify: MacOS | restart fortishield-agent
  tags:
    - init
    - config

- name: macOS | Check if client.keys exists
  stat:
    path: "{{ macos_fortishield_dir }}/etc/client.keys"
  register: client_keys_file
  tags:
    - config

- name: macOS | Set local_internal_options.conf
  template:
    src: var-ossec-etc-local-internal-options.conf.j2
    dest: "{{ macos_fortishield_dir }}/etc/local_internal_options.conf"
    owner: root
    group: fortishield
    mode: 0640
  notify: MacOS | restart fortishield-agent
  tags:
    - init
    - config

- name: Create auto-enrollment password file
  template:
    src: authd_pass.j2
    dest: "{{ macos_fortishield_dir }}/etc/authd.pass"
    owner: fortishield
    group: fortishield
    mode: 0640
  when:
    - fortishield_agent_config.enrollment.enabled == 'yes'
    - fortishield_agent_config.enrollment.authorization_pass_path | length > 0
    - authd_pass | length > 0
  tags:
    - config
