---
- block:
  - name: Copy Filebeat configuration.
    template:
      src: filebeat.yml.j2
      dest: "/etc/filebeat/filebeat.yml"
      owner: root
      group: root
      mode: 0400
    notify: restart filebeat

  - name: Fetch latest Fortishield alerts template
    get_url:
      url: https://raw.githubusercontent.com/fortishield/fortishield/{{ fortishield_template_branch }}/extensions/elasticsearch/7.x/fortishield-template.json
      dest: "/etc/filebeat/fortishield-template.json"
      owner: root
      group: root
      mode: 0400
    notify: restart filebeat

  tags:
  - configure
