---
- name: RedHat/CentOS/Fedora/Amazon Linux | Install Filebeats repo
  yum_repository:
    name: fortishield_repo
    description: Fortishield Repo
    baseurl: "{{ filebeatrepo.yum }}"
    gpgkey: "{{ filebeatrepo.gpg }}"
    gpgcheck: true
  changed_when: false
