version: 1
formatters:
  simple:
    format: '[%(asctime)s] [%(levelname)s] %(name)s: %(message)s'
  colored:
    (): colorlog.ColoredFormatter
    format: '%(log_color)s[%(asctime)s] [%(levelname)s] %(name)s: %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
filters:
  uppercase:
    (): modules.generic.logger.filters.UppercaseNameFilter
handlers:
  console:
    class: colorlog.StreamHandler
    level: DEBUG
    formatter: colored
    stream: ext://sys.stdout
    filters: [uppercase]
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: /tmp/deployability.log
    filters: [uppercase]
root:
  level: DEBUG
  handlers: [console, file]
