---
- name: restart fortishield-agent
  service: name=fortishield-agent state=restarted enabled=yes

- name: Windows | Restart Fortishield Agent
  win_service: name=FortishieldSvc start_mode=auto state=restarted

- name: MacOS | Restart Fortishield Agent
  shell: "{{ macos_fortishield_dir }}/bin/fortishield-control restart"
