- hosts: Manager*
  become: true
  tasks:
    - name: Enable and start Wazuh service
      command: "{{ item }}"
      with_items:
        - "systemctl daemon-reload"
        - "systemctl enable wazuh-manager"
        - "systemctl start wazuh-manager"

- hosts: Agent*
  become: true
  tasks:
    - name: Enable and start Wazuh service
      command: "{{ item }}"
      with_items:
        - "systemctl daemon-reload"
        - "systemctl enable wazuh-agent"
        - "systemctl start wazuh-agent"