fortishield_repo:
  apt: 'deb https://fortishield.github.io/packages-dev/staging/apt/ unstable main'
  yum: 'https://fortishield.github.io/packages-dev/staging/yum/'
  gpg: 'https://fortishield.github.io/packages-dev/key/GPG-KEY-FORTISHIELD'
  key_id: '0DCFCA5547B19D2A6099506096B3EE5F29111145'
fortishield_winagent_config_url: "https://fortishield.github.io/packages-dev/staging/windows/fortishield-agent-{{ fortishield_agent_version }}-1.msi"
fortishield_winagent_package_name: "fortishield-agent-{{ fortishield_agent_version }}-1.msi"

certs_gen_tool_version: 4.8

# Url of certificates generator tool
certs_gen_tool_url: "https://fortishield.github.io/packages-dev/{{ certs_gen_tool_version }}/fortishield-certs-tool.sh"